import type { Metadata } from "next";
// import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { ThemeProvider } from "@/providers/theme-provider";
import React from "react";
import { dark } from "@clerk/themes";
import { cn } from "@/lib/utils";

// const IBMPlex = IBM_Plex_Sans({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-ibn-plex",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ClerkProvider appearance={{ baseTheme: dark }}>
        <html lang="en" suppressHydrationWarning>
          <head />
          <body>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <body
              // className={cn("font-IBMPlex antialiased", IBMPlex.variable)}

              // There is an issue regarding within adding shadcn so i remove the styling till last
              >
                {children}
              </body>
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
